#! /usr/bin/env python3
import brktimeFunc

if __name__ == "__main__":
    [minsPassed, minsRemaining] = brktimeFunc.calcMinsPassedAndRemaining()
    print('Passed:', str(minsPassed).rjust(5),  'minutes')
    print('Till break:', minsRemaining, 'minutes')
